grafana:
  namespaceOverride: "observability"
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.feri-devops-machine.deploy-at.my.id
    annotations: 
      ingress.kubernetes.io/ssl-redirect: 'false'
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'false'
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  adminUser: admin
  adminPassword: strongpassword
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Mimir
          type: prometheus
          access: proxy
          url: http://mimir-gateway.observability.svc.cluster.local/prometheus
          isDefault: true
