apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cloud-b-cluster-1

servers: 1
agents: 2

registries:
  config: | # tell K3s to use this registry when pulling from DockerHub
    mirrors:
      "docker.io":
        endpoint:
          - http://k3d-docker-io:5000
      "quay.io":
        endpoint:
          - http://k3d-quay-io:5000

image: rancher/k3s:latest

ports:
  - port: 6443:6443
    nodeFilters:
      - server:*
  - port: 8181:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer


# Node labels
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
    nodeLabels:
      - label: cloud=b
        nodeFilters:
          - agent:*
          - server:*


# Volumes to mount
volumes:
  - volume: /tmp/k3d-storage:/tmp/storage
    nodeFilters:
      - agent:*
