{{- if .Values.minioCustomIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-minio-custom
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    {{- with .Values.minioCustomIngress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.minioCustomIngress.ingressClassName }}
  rules:
    {{- range .Values.minioCustomIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                # We still point to the service created by mimir-distributed
                name: {{ $.Release.Name }}-minio
                port:
                  number: 9000
          {{- end }}
    {{- end }}
{{- end }}